### ISSUE TITLE
A file "--file_path" is missing, which is important to generate the official testing dataset.

### ISSUE THREAD

**Issue by Hongje** [nowsyn/DVM#6]
Thank you for sharing a large-scale video matting dataset.
By the way, I want to generate the official testing dataset, but it seems that an important file is missing.
In `data/process.py`, an input argument "--file_path" is needed to generate fg-bg pairs, but I cannot find it.
Can you share this file? It would be really helpful for conducting a fair comparison with your DVM paper.

**Comment by nowsyn** [comment]
See data/test_fg_bg_names.txt.
